// JavaScript Andres Ivanov
var vse=300;
var o1=vse*0.45;
var _1=vse-o1;
var vse2=120;
var o2=vse2*0.64;
var _2=vse2-o2;
var vse3=60104;
var o3=vse3*0.429;
var _3=vse3-o3;
var vse4=52;
var o4=vse4*0.25;
var o44=vse4*0.10;
var o444=vse4*0.08;
var o4444=vse4*0.02;
var o44444=vse4*0.45;
var o444444=vse4-o44444;
var _4=o4+o44+o444+o4444+o444444;
var o5=45;
var o55=32;
var o555=o55/o5;
var _5=o555*60;
var o6=150000;
var _6=o6/3;
var o7=678;
var o77=102;
var o777=(678/2)-o77;
var _7=o77*o777;
var o8=5.5;
var o88=3.4;
var o888=2.8;
var _8=o8*o88*o888;
var o9=90;
var o99=60;
var o999=(o9+o99)/2;
var _9=o9-o999;
var o10=75;
var _10=o10*60;
var o11=34;
var _11=90-34;
var _12=(100*10)/5;
var o13=36;
var oo13=o13/3;
var _13=oo13+(oo13+oo13);
var _14=0.30*2;
document.write("1 ответ:&nbsp;");
document.write(o1);
document.write("&nbsp;и&nbsp;");
document.write(_1);
document.write("<br>3 ответ:&nbsp");
document.write(_2);
document.write("&nbsp; on isa kulud loeteldud otstarveteks.<br>4 ответ:&nbsp");
document.write(o3);
document.write("&nbsp; мужчин и&nbsp;");
document.write(_3);
document.write("&nbsp;женщин<br>6 ответ:&nbsp;");
document.write(o44444);
document.write("&nbsp;künnimaa,&nbsp;");
document.write(o4);
document.write("&nbsp;metsamaad,&nbsp;");
document.write(o44);
document.write("&nbsp;heinamaad,&nbsp;");
document.write(o444);
document.write("&nbsp;karjamaad,&nbsp;");
document.write(o4444);
document.write("&nbsp;kõlbmatut maad,&nbsp;");
document.write(_4);
document.write("&nbsp;kõik maad.&nbsp;<br>8 ответ:&nbsp;");
document.write(_5);
document.write("&nbsp; км проехал поезд за час.<br>9 ответ:&nbsp;");
document.write(_6);
document.write(".<br>10 ответ:&nbsp;Ristküliku pindala on&nbsp;");
document.write(_7);
document.write("&nbsp;dm.<br>11 ответ:&nbsp;");
document.write(_8);
document.write("&nbsp;m.<br>12 ответ:&nbsp;");
document.write(_9);
document.write("&nbsp;pähkleid.<br>13 ответ:&nbsp;");
document.write(_10);
document.write("&nbsp;lööki teeb pulss ühe tunnis.<br>14 ответ:&nbsp;");
document.write(_11);
document.write("&nbsp;teine nurk.<br>15 ответ:&nbsp;");
document.write(_12);
document.write("&nbsp;.<br>16 ответ:&nbsp;");
document.write(_13);
document.write("&nbsp;kõblast ja labidat anti õpilastele.<br>17 ответ:&nbsp;");
document.write(_14);
document.write("&nbsp;marka maksab 1kg.<br>18 ответ:&nbsp;");
document.write("<form method='post' name='pands'> <input type='text' value='Процент от числа' size='46' maxlength='11' name='pro' onfocus='if (this.value == 'Процент от числа') this.value = '';'><br> <input type='text' value='Число' size='46' maxlength='11' name='numb' onfocus='if (this.value == 'Число') this.value = '';'><br> <input type='button' value='Рассчитать от которого числа %' onClick='s()'></form>");
function s()
{
	
var x=parseInt(document.pands.pro.value);
var c=parseInt(document.pands.numb.value);
var p=100*c;
var s=p/x;
alert(s);
}
document.write("&nbsp;<br>19 ответ:&nbsp;");
document.write("<form method='post' name='proc'> <input type='text' value='Надо было сделать' size='46' maxlength='11' name='nado' onfocus='if (this.value == 'Надо было сделать') this.value = '';'><br> <input type='text' value='Сделано' size='46' maxlength='11' name='sdelano' onfocus='if (this.value == 'Сделано') this.value = '';'><br> <input type='button' value='На сколько % > или <' onClick='ss()'></form>");
function ss()
{
	
var xx=parseInt(document.proc.nado.value);
var cc=parseInt(document.proc.sdelano.value);
var pp=100*cc;
var ss=pp/xx;
alert(ss+ "%");
}